#!/bin/bash
# Lista de los usuarios en FotoSploit VIP
bane="baneado"
razon="~/.resultado1"
ex="expiro"

if [ ! -z $1 ] || [ ! -z $2 ]; then
	case $1 in
"Barbas")
;;
"Cia228")
;;
"Miickeyy")
;;
"Fabr1x")
	;;
"Cesar-Estrada")
		;;
"The_Predator")
		;;
	*)
echo "no" >> ~/.resultado
exit
;;
esac
case $2 in
"Bl4ckb34rd")
echo "si" >> ~/.resultado
;;
"Mati125689437")
echo "si" >> ~/.resultado
;;
"Miickeyy")
echo "si" >> ~/.resultado
;;
	"Metasploit07")
echo "si" >> ~/.resultado
;;
	"super1sonic")
echo "si" >> ~/.resultado
;;
	"gratis")
echo "$ex" >> ~/.resultado
;;
*)
echo "no" >> ~/.resultado
exit
;;
esac
else
	exit
fi
